indoor_daylight:
  hsv_low: [100, 120, 70]
  hsv_high: [130, 255, 255]
  min_area: 500
  consecutive_frames: 5
  roi: [200, 150, 200, 200]  

dim_room:
  hsv_low: [100, 100, 30]
  hsv_high: [130, 255, 200]
  min_area: 300
  consecutive_frames: 3
  roi: [200, 150, 200, 200]

red_object:
  hsv_low: [0, 120, 70]
  hsv_high: [10, 255, 255]
  min_area: 400
  consecutive_frames: 4
  roi: [200, 150, 200, 200]

red_object_upper:
  hsv_low: [170, 120, 70]
  hsv_high: [180, 255, 255]
  min_area: 400
  consecutive_frames: 4
  roi: [200, 150, 200, 200]